
name: Multi Platform Workflow

on:
  pull_request:
    branches:
      - master

jobs:

  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: uname -a
      - run: echo "Hello Ubuntu" > file.txt
      - run: cat file.txt

  windows-job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: systeminfo
      - run: echo Hello Windows > file.txt
      - run: type file.txt

  macos-job:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: uname -a
      - run: echo "Hello Mac" > file.txt
      - run: cat file.txt
